export const region = {
    Select: ["None Selected"],
    Africa: ["Northern Africa", "Sub-Saharan Africa"],
    Americas: ["Northern America", "Latin America and the Caribbean"],
    Asia: ["Central Asia", "Eastern Asia", "Southern Asia", "Western Asia"],
    Europe: [
        "Eastern Europe",
        "Northern Europe",
        "Western Europe",
        "Southern Europe",
    ],
    Oceania: [
        "Melanesia",
        "Micronesia",
        "Australia and New Zealand",
        "Polynesia",
    ],
    Global: ["All Regions"],
};

export const groupedRegions = [
    {
        label: "Africa",
        options: ["Northern Africa", "Sub-Saharan Africa"],
    },
    {
        label: "Americas",
        options: ["Northern America", "Latin America and the Caribbean"],
    },
    {
        label: "Asia",
        options: [
            "Central Asia",
            "Eastern Asia",
            "Southern Asia",
            "Western Asia",
        ],
    },
    {
        label: "Europe",
        options: [
            "Eastern Europe",
            "Northern Europe",
            "Western Europe",
            "Southern Europe",
        ],
    },
    {
        label: "Oceania",
        options: [
            "Melanesia",
            "Micronesia",
            "Australia and New Zealand",
            "Polynesia",
        ],
    },
    {
        label: "Global",
        options: ["All regions"],
    },
];

export const groupedIndustries = [
	{ label: "Generalist", options: ["Generalist"] },
	{ 
		label: "Sectors", 
		options: [
			'Consumer Goods',
			'Extractives & Minerals Processing',
			'Food & Beverage',
			'Financials',
			'Health Care',
			'Infrastructure',
			'Renewable Resources & Alternative Energy',
			'Resource Transformation',
			'Services',
			'Technology & Communications',
			'Transportation',
	]},

	{ 
		label: "Consumer Goods", 
		options: [
			'Apparel, Accessories & Footwear',
			'Appliance Manufacturing',
			'Building Products & Furnishings',
			'E-Commerce',
			'Household & Personal Products',
			'Multiline and Specialty Retailers & Distributors',
			'Toys & Sporting Goods',
	]},
	{ 
		label: "Extractives & Minerals Processing", 
		options: [
			'Construction Materials',
			'Coal Operations',
			'Oil & Gas – Exploration & Production',
			'Iron & Steel Producers',
			'Oil & Gas – Midstream',
			'Metals & Mining',
			'Oil & Gas – Refining & Marketing',
			'Oil & Gas – Services',
		
		]},
	{ 
		label: "Food & Beverage", 
		options: [
			'Alcoholic Beverages',
			'Agricultural Products',
			'Food Retailers & Distributors',
			'Meat, Poultry & Dairy',
			'Non-Alcoholic Beverages',
			'Processed Foods',
			'Restaurants',
			'Tobacco',
	]},
	{ 
		label: "Financials", 
		options: [
			'Asset Management & Custody Activities',
			'Commercial Banks',
			'Consumer Finance',
			'Security & Commodity Exchanges',
			'Investment Banking & Brokerage',
			'Insurance',
			'Mortgage Finance',	
		]},
	{ 
		label: "Health Care", 
		options: [
			'Biotechnology & Pharmaceuticals',
			'Health Care Distributors',
			'Drug Retailers',
			'Health Care Delivery',
			'Managed Care',
			'Medical Equipment & Supplies',
	]},
	{ 
		label: "Infrastructure", 
		options: [
			'Engineering & Construction Services',
			'Electric Utilities & Power Generators',
			'Gas Utilities & Distributors',
			'Home Builders',
			'Real Estate',
			'Real Estate Services',
			'Waste Management',
			'Water Utilities & Services',
	]},
	{ 
		label: "Renewable Resources & Alternative Energy", 
		options: [
			'Biofuels',
			'Fuel Cells & Industrial Batteries',
			'Forestry Management',
			'Pulp & Paper Products',
			'Solar Technology & Project Developers',
			'Wind Technology & Project Developers',
	]},
	{ 
		label: "Resource Transformation", 
		options: [
			'Aerospace & Defense',
			'Chemicals',
			'Containers & Packaging',
			'Electrical & Electronic Equipment',
			'Industrial Machinery & Goods',
	]},
	{ 
		label: "Services", 
		options: [
			'Advertising & Marketing',
			'Casinos & Gaming',
			'Education',
			'Hotels & Lodging',
			'Leisure Facilities',
			'Media & Entertainment',
			'Professional & Commercial Services',
	]},
	{ 
		label: "Technology & Communications", 
		options: [
			'Electronic Manufacturing Services & Original Design Manufacturing',
			'Hardware',
			'Internet Media & Services',
			'Semiconductors',
			'Software & IT Services',
			'Telecommunication Services',
	]},
	{ 
		label: "Transportation", 
		options: [
			'Air Freight & Logistics',
			'Airlines',
			'Auto Parts',
			'Automobiles',
			'Cruise Lines',
			'Car Rental & Leasing',
			'Marine Transportation',
			'Rail Transportation',
			'Road Transportation',
	]},




];

export const groupedIndustriesOld = [
    {
        label: "Oil and Gas",
        options: [
            "Exploration & Production",
            "Integrated Oil & Gas",
            "Oil Equipment & Services",
            "Pipelines",
            "Renewable Energy Equipment",
            "Alternative Fuels",
        ],
    },
    {
        label: "Basic Materials",
        options: [
            "Commodity Chemicals",
            "Specialty Chemicals",
            "Forestry",
            "Paper",
            "Aluminum",
            "Nonferrous Metals",
            "Iron & Steel",
            "Coal",
            "Diamonds & Gemstones",
            "General Mining",
            "Gold Mining",
            "Platinum & Precious Metals",
        ],
    },
    {
        label: "Industrials",
        options: [
            "Building Materials & Fixtures",
            "Heavy Construction",
            "Aerospace",
            "Defense",
            "Containers & Packaging",
            "Diversified Industrials",
            "Electrical Components & Equipment",
            "Electronic Equipment",
            "Commercial Vehicles & Trucks",
            "Industrial Machinery",
            "Delivery Services",
            "Marine Transportation",
            "Railroads",
            "Transportation Services",
            "Trucking",
            "Business Support Services",
            "Business Training & Employment Agencies",
            "Financial Administration",
            "Industrial Suppliers",
            "Waste & Disposal Services",
        ],
    },
    {
        label: "Consumer Goods",
        options: [
            "Automobiles",
            "Auto Parts",
            "Tires",
            "Brewers",
            "Distillers & Vintners",
            "Soft Drinks",
            "Farming & Fishing",
            "Food Products",
            "Durable Household Products",
            "Nondurable Household Products",
            "Furnishings",
            "Home Construction",
            "Consumer Electronics",
            "Recreational Products",
            "Toys",
            "Clothing & Accessories",
            "Footwear",
            "Personal Products",
            "Tobacco",
        ],
    },
    {
        label: "Healthcare",
        options: [
            "Health Care Providers",
            "Medical Equipment",
            "Medical Supplies",
            "Biotechnology",
            "Pharmaceuticals",
        ],
    },
    {
        label: "Consumer Services",
        options: [
            "Drug Retailers",
            "Food Retailers & Wholesalers",
            "Apparel Retailers",
            "Broadline Retailers",
            "Home Improvement Retailers",
            "Specialized Consumer Services",
            "Specialty Retailers",
            "Broadcasting & Entertainment",
            "Media Agencies",
            "Publishing",
            "Airlines",
            "Gambling",
            "Hotels",
            "Recreational Services",
            "Restaurants & Bars",
            "Travel & Tourism",
        ],
    },
    {
        label: "Utilities",
        options: [
            "Conventional Electricity",
            "Alternative Electricity",
            "Gas Distribution",
            "Multiutilities",
            "Water",
        ],
    },
    {
        label: "Telecommunications",
        options: ["Fixed Line Telecommunications", "Mobile Telecommunications"],
    },
    {
        label: "Financials",
        options: [
            "Banks",
            "Full Line Insurance",
            "Insurance Brokers",
            "Property & Casualty Insurance",
            "Reinsurance",
            "Life Insurance",
            "Real Estate Holding & Development",
            "Real Estate Services",
            "Industrial & Office REITs",
            "Retail REITs",
            "Residential REITs",
            "Diversified REITs",
            "Specialty REITs",
            "Mortgage REITs",
            "Hotel & Lodging REITs",
            "Asset Managers",
            "Consumer Finance",
            "Specialty Finance",
            "Investment Services",
            "Mortgage Finance",
            "Equity Investment Instrumentsv",
            "Nonequity Investment Instruments",
        ],
    },
    {
        label: "Technology",
        options: [
            "Computer Services",
            "Internet",
            "Software",
            "Computer Hardware",
            "Electronic Office Equipment",
            "Semiconductors",
            "Telecommunications Equipment",
        ],
    },
    {
        label: "Generialist",
        options: ["All"],
    },
];

export const industry = {
    Select: ["None Selected"],
    Generalist: ["All"],
    Oil_And_Gas: [
        "Exploration & Production",
        "Integrated Oil & Gas",
        "Oil Equipment & Services",
        "Pipelines",
        "Renewable Energy Equipment",
        "Alternative Fuels",
    ],
    Basic_Materials: [
        "Commodity Chemicals",
        "Specialty Chemicals",
        "Forestry",
        "Paper",
        "Aluminum",
        "Nonferrous Metals",
        "Iron & Steel",
        "Coal",
        "Diamonds & Gemstones",
        "General Mining",
        "Gold Mining",
        "Platinum & Precious Metals",
    ],
    Industrials: [
        "Building Materials & Fixtures",
        "Heavy Construction",
        "Aerospace",
        "Defense",
        "Containers & Packaging",
        "Diversified Industrials",
        "Electrical Components & Equipment",
        "Electronic Equipment",
        "Commercial Vehicles & Trucks",
        "Industrial Machinery",
        "Delivery Services",
        "Marine Transportation",
        "Railroads",
        "Transportation Services",
        "Trucking",
        "Business Support Services",
        "Business Training & Employment Agencies",
        "Financial Administration",
        "Industrial Suppliers",
        "Waste & Disposal Services",
    ],
    Consumer_Goods: [
        "Automobiles",
        "Auto Parts",
        "Tires",
        "Brewers",
        "Distillers & Vintners",
        "Soft Drinks",
        "Farming & Fishing",
        "Food Products",
        "Durable Household Products",
        "Nondurable Household Products",
        "Furnishings",
        "Home Construction",
        "Consumer Electronics",
        "Recreational Products",
        "Toys",
        "Clothing & Accessories",
        "Footwear",
        "Personal Products",
        "Tobacco",
    ],
    Health_Care: [
        "Health Care Providers",
        "Medical Equipment",
        "Medical Supplies",
        "Biotechnology",
        "Pharmaceuticals",
    ],
    Consumer_Services: [
        "Drug Retailers",
        "Food Retailers & Wholesalers",
        "Apparel Retailers",
        "Broadline Retailers",
        "Home Improvement Retailers",
        "Specialized Consumer Services",
        "Specialty Retailers",
        "Broadcasting & Entertainment",
        "Media Agencies",
        "Publishing",
        "Airlines",
        "Gambling",
        "Hotels",
        "Recreational Services",
        "Restaurants & Bars",
        "Travel & Tourism",
    ],
    Utilities: [
        "Conventional Electricity",
        "Alternative Electricity",
        "Gas Distribution",
        "Multiutilities",
        "Water",
    ],
    Telecommunications: [
        "Fixed Line Telecommunications",
        "Mobile Telecommunications",
    ],
    Financials: [
        "Banks",
        "Full Line Insurance",
        "Insurance Brokers",
        "Property & Casualty Insurance",
        "Reinsurance",
        "Life Insurance",
        "Real Estate Holding & Development",
        "Real Estate Services",
        "Industrial & Office REITs",
        "Retail REITs",
        "Residential REITs",
        "Diversified REITs",
        "Specialty REITs",
        "Mortgage REITs",
        "Hotel & Lodging REITs",
        "Asset Managers",
        "Consumer Finance",
        "Specialty Finance",
        "Investment Services",
        "Mortgage Finance",
        "Equity Investment Instrumentsv",
        "Nonequity Investment Instruments",
    ],
    Technology: [
        "Computer Services",
        "Internet",
        "Software",
        "Computer Hardware",
        "Electronic Office Equipment",
        "Semiconductors",
        "Telecommunications Equipment",
    ],
};
